# Generated by Django 3.2.7 on 2021-11-27 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarauthApp', '0002_user_adm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adm',
            new_name='admin',
        ),
    ]
